### ISSUE TITLE
[Note] 마우스로 포매팅

### ISSUE THREAD

**Issue by chahtk** [njsh4261/SGS_Last_Punch#149]
### 현재

현재 컨트롤 + b,i,u,` 로 포매팅을 줄 수 있음. (선점자여야 함)
그러나 마우스로 텍스트를 드래그하고 효과를 주는 것에 대해서는 선점 개념 미구현, update를 서버에 알리지 않음

### TODO

- [ ] 비선점자일 때 선점 요청 후 선점권 얻으면 효과 적용
- [ ] 다른 사람이 선점하고 있을 때 적용 금지
- [ ] 해당 내용 op큐에 넣기
- [ ] 실시간으로 다른 유저에게 적용되는지 확인
- [ ] mongoDB에 잘 적용되는지 확인
